#include "images.h"

const ext_img_desc_t images[27] = {
    { "power_icon", &img_power_icon },
    { "reboot_icon", &img_reboot_icon },
    { "brightness_icon", &img_brightness_icon },
    { "volume_icon", &img_volume_icon },
    { "backlight_icon", &img_backlight_icon },
    { "screen_icon", &img_screen_icon },
    { "rotate_icon", &img_rotate_icon },
    { "wifi_icon", &img_wifi_icon },
    { "return_icon", &img_return_icon },
    { "config_icon", &img_config_icon },
    { "reset_icon", &img_reset_icon },
    { "check_icon", &img_check_icon },
    { "refresh_icon", &img_refresh_icon },
    { "play_icon", &img_play_icon },
    { "pause_icon", &img_pause_icon },
    { "timer_icon", &img_timer_icon },
    { "clockGauge", &img_clock_gauge },
    { "clock_needle_big", &img_clock_needle_big },
    { "clock_needle_small", &img_clock_needle_small },
    { "blue_gradient", &img_blue_gradient },
    { "background_red", &img_background_red },
    { "crypto_icon", &img_crypto_icon },
    { "stock_icon", &img_stock_icon },
    { "background_green", &img_background_green },
    { "logo_big", &img_logo_big },
    { "ai_icon", &img_ai_icon },
    { "cross_icon", &img_cross_icon },
};