// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: market_viewer

#include "ui.h"

lv_obj_t * ui_brightnessScreen = NULL;
lv_obj_t * ui_brightnessArc = NULL;
lv_obj_t * ui_brightnessLabel = NULL;
lv_obj_t * ui_brightnessValueLabel = NULL;
lv_obj_t * ui_brightnessButtonBack = NULL;
lv_obj_t * ui_brightnessIcon = NULL;
// event funtions
void ui_event_brightnessScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        saveBrightness(e);
    }
}

void ui_event_brightnessArc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_brightnessValueLabel, target, "", "%");
        setBrightnessFromArc(e);
    }
}

void ui_event_brightnessButtonBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_homeScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_homeScreen_screen_init);
        playButtonClickedSound(e);
    }
}

// build funtions

void ui_brightnessScreen_screen_init(void)
{
    ui_brightnessScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_brightnessScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_brightnessScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_brightnessScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_brightnessArc = lv_arc_create(ui_brightnessScreen);
    lv_obj_set_width(ui_brightnessArc, 400);
    lv_obj_set_height(ui_brightnessArc, 400);
    lv_obj_set_align(ui_brightnessArc, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_brightnessArc, 5, 100);
    lv_arc_set_value(ui_brightnessArc, 50);
    lv_obj_set_style_arc_width(ui_brightnessArc, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_brightnessArc, lv_color_hex(0x86A411), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_brightnessArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_brightnessArc, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_brightnessArc, lv_color_hex(0xE1D33D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_brightnessArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_brightnessArc, lv_color_hex(0xD1D724), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_brightnessArc, 200, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_brightnessArc, 30, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_brightnessArc, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_brightnessArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_brightnessArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_brightnessLabel = lv_label_create(ui_brightnessScreen);
    lv_obj_set_width(ui_brightnessLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_brightnessLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_brightnessLabel, 0);
    lv_obj_set_y(ui_brightnessLabel, 170);
    lv_obj_set_align(ui_brightnessLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_brightnessLabel, "BRIGHTNESS");
    ui_object_set_themeable_style_property(ui_brightnessLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_grayDark);
    ui_object_set_themeable_style_property(ui_brightnessLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_grayDark);
    lv_obj_set_style_text_font(ui_brightnessLabel, &ui_font_mono40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_brightnessValueLabel = lv_label_create(ui_brightnessScreen);
    lv_obj_set_width(ui_brightnessValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_brightnessValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_brightnessValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_brightnessValueLabel, "50%");
    ui_object_set_themeable_style_property(ui_brightnessValueLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_yellowDark);
    ui_object_set_themeable_style_property(ui_brightnessValueLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_yellowDark);
    lv_obj_set_style_text_font(ui_brightnessValueLabel, &ui_font_monoBold100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_brightnessButtonBack = lv_imgbtn_create(ui_brightnessScreen);
    lv_imgbtn_set_src(ui_brightnessButtonBack, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1702299517, NULL);
    lv_obj_set_width(ui_brightnessButtonBack, 50);
    lv_obj_set_height(ui_brightnessButtonBack, 50);
    lv_obj_set_x(ui_brightnessButtonBack, 0);
    lv_obj_set_y(ui_brightnessButtonBack, 100);
    lv_obj_set_align(ui_brightnessButtonBack, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_brightnessButtonBack, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_grayBright);
    ui_object_set_themeable_style_property(ui_brightnessButtonBack, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_grayBright);

    ui_brightnessIcon = lv_img_create(ui_brightnessScreen);
    lv_img_set_src(ui_brightnessIcon, &ui_img_1826884842);
    lv_obj_set_width(ui_brightnessIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_brightnessIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_brightnessIcon, 0);
    lv_obj_set_y(ui_brightnessIcon, -100);
    lv_obj_set_align(ui_brightnessIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_brightnessIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_brightnessIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_brightnessIcon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_grayBright);
    ui_object_set_themeable_style_property(ui_brightnessIcon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_grayBright);

    lv_obj_add_event_cb(ui_brightnessArc, ui_event_brightnessArc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_brightnessButtonBack, ui_event_brightnessButtonBack, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_brightnessScreen, ui_event_brightnessScreen, LV_EVENT_ALL, NULL);

}

void ui_brightnessScreen_screen_destroy(void)
{
    if(ui_brightnessScreen) lv_obj_del(ui_brightnessScreen);

    // NULL screen variables
    ui_brightnessScreen = NULL;
    ui_brightnessArc = NULL;
    ui_brightnessLabel = NULL;
    ui_brightnessValueLabel = NULL;
    ui_brightnessButtonBack = NULL;
    ui_brightnessIcon = NULL;

}
