// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: market_viewer

#include "ui.h"

lv_obj_t * ui_marketDataSettingScreen = NULL;
lv_obj_t * ui_marketDataSettingsLabel = NULL;
lv_obj_t * ui_marketDataSettingMainPanel = NULL;
lv_obj_t * ui_simpleDispalyCont = NULL;
lv_obj_t * ui_simpleDisplayLabel = NULL;
lv_obj_t * ui_simpleDisplaySwitch = NULL;
lv_obj_t * ui_displayGraphCont = NULL;
lv_obj_t * ui_displayChartLabel = NULL;
lv_obj_t * ui_displayGraphSwitch = NULL;
lv_obj_t * ui_candleChartCont = NULL;
lv_obj_t * ui_candleChartLabel = NULL;
lv_obj_t * ui_candleChartSwitch = NULL;
// event funtions
void ui_event_marketDataSettingScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        exitMarketDataSetting(e);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        marketDataSettingScreenLoad(e);
    }
}

void ui_event_simpleDisplaySwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        simpleDisplaySwitchToggle(e);
        playButtonClickedSound(e);
    }
}

void ui_event_displayGraphSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        displayGraphSwitchToggle(e);
        playButtonClickedSound(e);
    }
}

void ui_event_candleChartSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        candleChartSwitchToggle(e);
        playButtonClickedSound(e);
    }
}

// build funtions

void ui_marketDataSettingScreen_screen_init(void)
{
    ui_marketDataSettingScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_marketDataSettingScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_marketDataSettingScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_marketDataSettingScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_marketDataSettingScreen, &ui_img_green_background_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_marketDataSettingScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_marketDataSettingScreen, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_marketDataSettingsLabel = lv_label_create(ui_marketDataSettingScreen);
    lv_obj_set_width(ui_marketDataSettingsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_marketDataSettingsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_marketDataSettingsLabel, 0);
    lv_obj_set_y(ui_marketDataSettingsLabel, 190);
    lv_obj_set_align(ui_marketDataSettingsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_marketDataSettingsLabel, "SETTINGS");
    ui_object_set_themeable_style_property(ui_marketDataSettingsLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_grayDark);
    ui_object_set_themeable_style_property(ui_marketDataSettingsLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_grayDark);
    lv_obj_set_style_text_font(ui_marketDataSettingsLabel, &ui_font_mono40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_marketDataSettingMainPanel = lv_obj_create(ui_marketDataSettingScreen);
    lv_obj_set_width(ui_marketDataSettingMainPanel, 436);
    lv_obj_set_height(ui_marketDataSettingMainPanel, 330);
    lv_obj_set_align(ui_marketDataSettingMainPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_marketDataSettingMainPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_marketDataSettingMainPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_marketDataSettingMainPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_marketDataSettingMainPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_marketDataSettingMainPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_marketDataSettingMainPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_width(ui_marketDataSettingMainPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_simpleDispalyCont = lv_obj_create(ui_marketDataSettingMainPanel);
    lv_obj_set_width(ui_simpleDispalyCont, 427);
    lv_obj_set_height(ui_simpleDispalyCont, 66);
    lv_obj_set_align(ui_simpleDispalyCont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_simpleDispalyCont, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_simpleDispalyCont, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_simpleDispalyCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_simpleDispalyCont, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_simpleDispalyCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_simpleDispalyCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_simpleDisplayLabel = lv_label_create(ui_simpleDispalyCont);
    lv_obj_set_width(ui_simpleDisplayLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_simpleDisplayLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_simpleDisplayLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_simpleDisplayLabel, "Simple display");
    lv_obj_set_style_text_font(ui_simpleDisplayLabel, &ui_font_mono30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_simpleDisplaySwitch = lv_switch_create(ui_simpleDispalyCont);
    lv_obj_set_width(ui_simpleDisplaySwitch, 80);
    lv_obj_set_height(ui_simpleDisplaySwitch, 40);
    lv_obj_set_align(ui_simpleDisplaySwitch, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_simpleDisplaySwitch, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_simpleDisplaySwitch, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_object_set_themeable_style_property(ui_simpleDisplaySwitch, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_yellowDark);
    ui_object_set_themeable_style_property(ui_simpleDisplaySwitch, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_yellowDark);

    lv_obj_set_style_bg_color(ui_simpleDisplaySwitch, lv_color_hex(0xECECEC), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_simpleDisplaySwitch, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_displayGraphCont = lv_obj_create(ui_marketDataSettingMainPanel);
    lv_obj_set_width(ui_displayGraphCont, 427);
    lv_obj_set_height(ui_displayGraphCont, 66);
    lv_obj_set_align(ui_displayGraphCont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_displayGraphCont, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_displayGraphCont, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_displayGraphCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_displayGraphCont, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_displayGraphCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_displayGraphCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_displayChartLabel = lv_label_create(ui_displayGraphCont);
    lv_obj_set_width(ui_displayChartLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_displayChartLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_displayChartLabel, -1);
    lv_obj_set_y(ui_displayChartLabel, 0);
    lv_obj_set_align(ui_displayChartLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_displayChartLabel, "Display chart");
    lv_obj_set_style_text_font(ui_displayChartLabel, &ui_font_mono30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_displayGraphSwitch = lv_switch_create(ui_displayGraphCont);
    lv_obj_set_width(ui_displayGraphSwitch, 80);
    lv_obj_set_height(ui_displayGraphSwitch, 40);
    lv_obj_set_align(ui_displayGraphSwitch, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_displayGraphSwitch, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_displayGraphSwitch, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_object_set_themeable_style_property(ui_displayGraphSwitch, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_yellowDark);
    ui_object_set_themeable_style_property(ui_displayGraphSwitch, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_yellowDark);

    lv_obj_set_style_bg_color(ui_displayGraphSwitch, lv_color_hex(0xECECEC), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_displayGraphSwitch, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_candleChartCont = lv_obj_create(ui_marketDataSettingMainPanel);
    lv_obj_set_width(ui_candleChartCont, 427);
    lv_obj_set_height(ui_candleChartCont, 66);
    lv_obj_set_align(ui_candleChartCont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_candleChartCont, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_candleChartCont, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_candleChartCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_candleChartCont, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_candleChartCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_candleChartCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_candleChartLabel = lv_label_create(ui_candleChartCont);
    lv_obj_set_width(ui_candleChartLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_candleChartLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_candleChartLabel, -1);
    lv_obj_set_y(ui_candleChartLabel, 0);
    lv_obj_set_align(ui_candleChartLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_candleChartLabel, "Candle chart");
    lv_obj_set_style_text_font(ui_candleChartLabel, &ui_font_mono30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_candleChartSwitch = lv_switch_create(ui_candleChartCont);
    lv_obj_set_width(ui_candleChartSwitch, 80);
    lv_obj_set_height(ui_candleChartSwitch, 40);
    lv_obj_set_align(ui_candleChartSwitch, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_candleChartSwitch, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_candleChartSwitch, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_object_set_themeable_style_property(ui_candleChartSwitch, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_yellowDark);
    ui_object_set_themeable_style_property(ui_candleChartSwitch, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_yellowDark);

    lv_obj_set_style_bg_color(ui_candleChartSwitch, lv_color_hex(0xECECEC), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_candleChartSwitch, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_simpleDisplaySwitch, ui_event_simpleDisplaySwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_displayGraphSwitch, ui_event_displayGraphSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_candleChartSwitch, ui_event_candleChartSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_marketDataSettingScreen, ui_event_marketDataSettingScreen, LV_EVENT_ALL, NULL);

}

void ui_marketDataSettingScreen_screen_destroy(void)
{
    if(ui_marketDataSettingScreen) lv_obj_del(ui_marketDataSettingScreen);

    // NULL screen variables
    ui_marketDataSettingScreen = NULL;
    ui_marketDataSettingsLabel = NULL;
    ui_marketDataSettingMainPanel = NULL;
    ui_simpleDispalyCont = NULL;
    ui_simpleDisplayLabel = NULL;
    ui_simpleDisplaySwitch = NULL;
    ui_displayGraphCont = NULL;
    ui_displayChartLabel = NULL;
    ui_displayGraphSwitch = NULL;
    ui_candleChartCont = NULL;
    ui_candleChartLabel = NULL;
    ui_candleChartSwitch = NULL;

}
