// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: market_viewer

#include "ui.h"

lv_obj_t * ui_screensScreen = NULL;
lv_obj_t * ui_screenNotFetchedLabel = NULL;
lv_obj_t * ui_screensLabel = NULL;
lv_obj_t * ui_screensListPanel = NULL;
lv_obj_t * ui_screenListItemLabelExample = NULL;
lv_obj_t * ui_volumeButtonBack3 = NULL;
lv_obj_t * ui_screensRefetchButton = NULL;
// event funtions
void ui_event_screensScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        handleScreensScreenLoad(e);
    }
}

void ui_event_volumeButtonBack3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_homeScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_homeScreen_screen_init);
        playButtonClickedSound(e);
    }
}

void ui_event_screensRefetchButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        refetchScreens(e);
        playButtonClickedSound(e);
    }
}

// build funtions

void ui_screensScreen_screen_init(void)
{
    ui_screensScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screensScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screensScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screensScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_screenNotFetchedLabel = lv_label_create(ui_screensScreen);
    lv_obj_set_width(ui_screenNotFetchedLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_screenNotFetchedLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_screenNotFetchedLabel, 0);
    lv_obj_set_y(ui_screenNotFetchedLabel, -80);
    lv_obj_set_align(ui_screenNotFetchedLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_screenNotFetchedLabel, "No screens");
    ui_object_set_themeable_style_property(ui_screenNotFetchedLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_redDark);
    ui_object_set_themeable_style_property(ui_screenNotFetchedLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_redDark);
    lv_obj_set_style_text_font(ui_screenNotFetchedLabel, &ui_font_mono40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_screensLabel = lv_label_create(ui_screensScreen);
    lv_obj_set_width(ui_screensLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_screensLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_screensLabel, 0);
    lv_obj_set_y(ui_screensLabel, 190);
    lv_obj_set_align(ui_screensLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_screensLabel, "SCREENS");
    ui_object_set_themeable_style_property(ui_screensLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_grayDark);
    ui_object_set_themeable_style_property(ui_screensLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_grayDark);
    lv_obj_set_style_text_font(ui_screensLabel, &ui_font_mono40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_screensListPanel = lv_obj_create(ui_screensScreen);
    lv_obj_set_width(ui_screensListPanel, 320);
    lv_obj_set_height(ui_screensListPanel, 213);
    lv_obj_set_x(ui_screensListPanel, 0);
    lv_obj_set_y(ui_screensListPanel, -100);
    lv_obj_set_align(ui_screensListPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_screensListPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_screensListPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_screensListPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_scroll_dir(ui_screensListPanel, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_screensListPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screensListPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_screensListPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_screensListPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_screenListItemLabelExample = lv_label_create(ui_screensListPanel);
    lv_obj_set_width(ui_screenListItemLabelExample, 300);
    lv_obj_set_height(ui_screenListItemLabelExample, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_screenListItemLabelExample, 3);
    lv_obj_set_y(ui_screenListItemLabelExample, -85);
    lv_obj_set_align(ui_screenListItemLabelExample, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_screenListItemLabelExample, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_screenListItemLabelExample, "1. Stock screens");
    lv_obj_add_flag(ui_screenListItemLabelExample, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_align(ui_screenListItemLabelExample, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_screenListItemLabelExample, &ui_font_mono30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_volumeButtonBack3 = lv_imgbtn_create(ui_screensScreen);
    lv_imgbtn_set_src(ui_volumeButtonBack3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1702299517, NULL);
    lv_obj_set_width(ui_volumeButtonBack3, 50);
    lv_obj_set_height(ui_volumeButtonBack3, 50);
    lv_obj_set_x(ui_volumeButtonBack3, 0);
    lv_obj_set_y(ui_volumeButtonBack3, 140);
    lv_obj_set_align(ui_volumeButtonBack3, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_volumeButtonBack3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_grayBright);
    ui_object_set_themeable_style_property(ui_volumeButtonBack3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_grayBright);

    ui_screensRefetchButton = lv_btn_create(ui_screensScreen);
    lv_obj_set_width(ui_screensRefetchButton, 90);
    lv_obj_set_height(ui_screensRefetchButton, 90);
    lv_obj_set_x(ui_screensRefetchButton, 0);
    lv_obj_set_y(ui_screensRefetchButton, 50);
    lv_obj_set_align(ui_screensRefetchButton, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_screensRefetchButton, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_screensRefetchButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_screensRefetchButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_screensRefetchButton, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_screensRefetchButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_grayBright);
    ui_object_set_themeable_style_property(ui_screensRefetchButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_grayBright);
    lv_obj_set_style_bg_img_src(ui_screensRefetchButton, &ui_img_936315526, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_screensRefetchButton, LV_PART_MAIN | LV_STATE_DISABLED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_redDark);
    ui_object_set_themeable_style_property(ui_screensRefetchButton, LV_PART_MAIN | LV_STATE_DISABLED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_redDark);

    lv_obj_add_event_cb(ui_volumeButtonBack3, ui_event_volumeButtonBack3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_screensRefetchButton, ui_event_screensRefetchButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_screensScreen, ui_event_screensScreen, LV_EVENT_ALL, NULL);

}

void ui_screensScreen_screen_destroy(void)
{
    if(ui_screensScreen) lv_obj_del(ui_screensScreen);

    // NULL screen variables
    ui_screensScreen = NULL;
    ui_screenNotFetchedLabel = NULL;
    ui_screensLabel = NULL;
    ui_screensListPanel = NULL;
    ui_screenListItemLabelExample = NULL;
    ui_volumeButtonBack3 = NULL;
    ui_screensRefetchButton = NULL;

}
