// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: market_viewer

#include "ui.h"

lv_obj_t * ui_volumeScreen = NULL;
lv_obj_t * ui_volumeArc = NULL;
lv_obj_t * ui_volumeLabel = NULL;
lv_obj_t * ui_volumeValueLabel = NULL;
lv_obj_t * ui_volumeButtonBack = NULL;
lv_obj_t * ui_volumeIcon = NULL;
// event funtions
void ui_event_volumeScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        saveVolume(e);
    }
}

void ui_event_volumeArc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_volumeValueLabel, target, "", "%");
        setVolumeFromArc(e);
    }
}

void ui_event_volumeButtonBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_homeScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_homeScreen_screen_init);
        playButtonClickedSound(e);
    }
}

// build funtions

void ui_volumeScreen_screen_init(void)
{
    ui_volumeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_volumeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_volumeScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_volumeScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_volumeArc = lv_arc_create(ui_volumeScreen);
    lv_obj_set_width(ui_volumeArc, 400);
    lv_obj_set_height(ui_volumeArc, 400);
    lv_obj_set_align(ui_volumeArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_volumeArc, 50);
    lv_obj_set_style_arc_width(ui_volumeArc, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_volumeArc, lv_color_hex(0x86A411), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_volumeArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_volumeArc, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_volumeArc, lv_color_hex(0xE1D33D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_volumeArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_volumeArc, lv_color_hex(0xD1D724), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_volumeArc, 200, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_volumeArc, 30, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_volumeArc, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_volumeArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_volumeArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_volumeLabel = lv_label_create(ui_volumeScreen);
    lv_obj_set_width(ui_volumeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_volumeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_volumeLabel, 0);
    lv_obj_set_y(ui_volumeLabel, 170);
    lv_obj_set_align(ui_volumeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_volumeLabel, "VOLUME");
    ui_object_set_themeable_style_property(ui_volumeLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_grayDark);
    ui_object_set_themeable_style_property(ui_volumeLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_grayDark);
    lv_obj_set_style_text_font(ui_volumeLabel, &ui_font_mono40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_volumeValueLabel = lv_label_create(ui_volumeScreen);
    lv_obj_set_width(ui_volumeValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_volumeValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_volumeValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_volumeValueLabel, "50%");
    ui_object_set_themeable_style_property(ui_volumeValueLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_yellowDark);
    ui_object_set_themeable_style_property(ui_volumeValueLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_yellowDark);
    lv_obj_set_style_text_font(ui_volumeValueLabel, &ui_font_monoBold100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_volumeButtonBack = lv_imgbtn_create(ui_volumeScreen);
    lv_imgbtn_set_src(ui_volumeButtonBack, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1702299517, NULL);
    lv_obj_set_width(ui_volumeButtonBack, 50);
    lv_obj_set_height(ui_volumeButtonBack, 50);
    lv_obj_set_x(ui_volumeButtonBack, 0);
    lv_obj_set_y(ui_volumeButtonBack, 100);
    lv_obj_set_align(ui_volumeButtonBack, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_volumeButtonBack, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_grayBright);
    ui_object_set_themeable_style_property(ui_volumeButtonBack, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_grayBright);

    ui_volumeIcon = lv_img_create(ui_volumeScreen);
    lv_img_set_src(ui_volumeIcon, &ui_img_367695115);
    lv_obj_set_width(ui_volumeIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_volumeIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_volumeIcon, 0);
    lv_obj_set_y(ui_volumeIcon, -100);
    lv_obj_set_align(ui_volumeIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_volumeIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_volumeIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_volumeIcon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_grayBright);
    ui_object_set_themeable_style_property(ui_volumeIcon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_grayBright);

    lv_obj_add_event_cb(ui_volumeArc, ui_event_volumeArc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_volumeButtonBack, ui_event_volumeButtonBack, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_volumeScreen, ui_event_volumeScreen, LV_EVENT_ALL, NULL);

}

void ui_volumeScreen_screen_destroy(void)
{
    if(ui_volumeScreen) lv_obj_del(ui_volumeScreen);

    // NULL screen variables
    ui_volumeScreen = NULL;
    ui_volumeArc = NULL;
    ui_volumeLabel = NULL;
    ui_volumeValueLabel = NULL;
    ui_volumeButtonBack = NULL;
    ui_volumeIcon = NULL;

}
