// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: market_viewer

#include "ui.h"

lv_obj_t * ui_wifiScreen = NULL;
lv_obj_t * ui_mainContainerWifi = NULL;
lv_obj_t * ui_connectionInfoContainer = NULL;
lv_obj_t * ui_wifiConnectionRoundIndicator = NULL;
lv_obj_t * ui_connectionLabel = NULL;
lv_obj_t * ui_connectedWifiContainer = NULL;
lv_obj_t * ui_wifiNameContainer = NULL;
lv_obj_t * ui_connectedWifiSSIDLabel = NULL;
lv_obj_t * ui_connectedWifiIcon = NULL;
lv_obj_t * ui_backendUrlLabel = NULL;
lv_obj_t * ui_wifiContainersButtons = NULL;
lv_obj_t * ui_wifiConfigButton = NULL;
lv_obj_t * ui_wifiResetButton = NULL;
lv_obj_t * ui_wifiLabel = NULL;
lv_obj_t * ui_volumeButtonBack2 = NULL;
lv_obj_t * ui_overlayWifiContainer = NULL;
lv_obj_t * ui_overlayWifiLabel1 = NULL;
lv_obj_t * ui_overlayWifiSSIDLabel = NULL;
lv_obj_t * ui_overlayWifiSSIDLabelValue = NULL;
lv_obj_t * ui_overlayWifiPwdLabel = NULL;
lv_obj_t * ui_overlayWifiPwdLabelValue = NULL;
// event funtions
void ui_event_wifiScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        elementBlink_Animation(ui_wifiConnectionRoundIndicator, 0);
        updateWifiScreenStatusOnLoad(e);
    }
}

void ui_event_wifiConfigButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        openWifiPortal(e);
        playButtonClickedSound(e);
    }
}

void ui_event_wifiResetButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        resetWifiConfig(e);
        playButtonClickedSound(e);
    }
}

void ui_event_volumeButtonBack2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_homeScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_homeScreen_screen_init);
        playButtonClickedSound(e);
    }
}

// build funtions

void ui_wifiScreen_screen_init(void)
{
    ui_wifiScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_wifiScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_wifiScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifiScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainContainerWifi = lv_obj_create(ui_wifiScreen);
    lv_obj_set_width(ui_mainContainerWifi, 400);
    lv_obj_set_height(ui_mainContainerWifi, 316);
    lv_obj_set_x(ui_mainContainerWifi, 0);
    lv_obj_set_y(ui_mainContainerWifi, -25);
    lv_obj_set_align(ui_mainContainerWifi, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_mainContainerWifi, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_mainContainerWifi, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_mainContainerWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mainContainerWifi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainContainerWifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_mainContainerWifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_mainContainerWifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connectionInfoContainer = lv_obj_create(ui_mainContainerWifi);
    lv_obj_set_width(ui_connectionInfoContainer, 416);
    lv_obj_set_height(ui_connectionInfoContainer, 52);
    lv_obj_set_x(ui_connectionInfoContainer, -8);
    lv_obj_set_y(ui_connectionInfoContainer, -62);
    lv_obj_set_align(ui_connectionInfoContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_connectionInfoContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_connectionInfoContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_connectionInfoContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_connectionInfoContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_connectionInfoContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_connectionInfoContainer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_connectionInfoContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiConnectionRoundIndicator = lv_obj_create(ui_connectionInfoContainer);
    lv_obj_remove_style_all(ui_wifiConnectionRoundIndicator);
    lv_obj_set_width(ui_wifiConnectionRoundIndicator, 30);
    lv_obj_set_height(ui_wifiConnectionRoundIndicator, 30);
    lv_obj_set_align(ui_wifiConnectionRoundIndicator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_wifiConnectionRoundIndicator, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_wifiConnectionRoundIndicator, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_wifiConnectionRoundIndicator, lv_color_hex(0xF10404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifiConnectionRoundIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connectionLabel = lv_label_create(ui_connectionInfoContainer);
    lv_obj_set_width(ui_connectionLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_connectionLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_connectionLabel, 51);
    lv_obj_set_y(ui_connectionLabel, -82);
    lv_obj_set_align(ui_connectionLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_connectionLabel, "NOT CONNECTED");
    lv_obj_set_style_text_font(ui_connectionLabel, &ui_font_mono40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connectedWifiContainer = lv_obj_create(ui_mainContainerWifi);
    lv_obj_set_width(ui_connectedWifiContainer, 379);
    lv_obj_set_height(ui_connectedWifiContainer, 102);
    lv_obj_set_x(ui_connectedWifiContainer, -48);
    lv_obj_set_y(ui_connectedWifiContainer, -30);
    lv_obj_set_align(ui_connectedWifiContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_connectedWifiContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_connectedWifiContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_connectedWifiContainer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_connectedWifiContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_connectedWifiContainer, &ui_font_Mono20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiNameContainer = lv_obj_create(ui_connectedWifiContainer);
    lv_obj_set_width(ui_wifiNameContainer, 248);
    lv_obj_set_height(ui_wifiNameContainer, 39);
    lv_obj_set_align(ui_wifiNameContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_wifiNameContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_wifiNameContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_wifiNameContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_wifiNameContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connectedWifiSSIDLabel = lv_label_create(ui_wifiNameContainer);
    lv_obj_set_width(ui_connectedWifiSSIDLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_connectedWifiSSIDLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_connectedWifiSSIDLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_connectedWifiSSIDLabel, "Wifi name");
    lv_obj_set_style_text_font(ui_connectedWifiSSIDLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connectedWifiIcon = lv_img_create(ui_wifiNameContainer);
    lv_img_set_src(ui_connectedWifiIcon, &ui_img_536642073);
    lv_obj_set_width(ui_connectedWifiIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_connectedWifiIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_connectedWifiIcon, 90);
    lv_obj_set_y(ui_connectedWifiIcon, -20);
    lv_obj_set_align(ui_connectedWifiIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_connectedWifiIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_connectedWifiIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_connectedWifiIcon, lv_color_hex(0x2CB60C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_connectedWifiIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backendUrlLabel = lv_label_create(ui_connectedWifiContainer);
    lv_obj_set_width(ui_backendUrlLabel, 367);
    lv_obj_set_height(ui_backendUrlLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_backendUrlLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_backendUrlLabel, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_backendUrlLabel, "http://localhost:8080/api");
    lv_obj_set_style_text_color(ui_backendUrlLabel, lv_color_hex(0x9C9C9C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_backendUrlLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_backendUrlLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_backendUrlLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiContainersButtons = lv_obj_create(ui_mainContainerWifi);
    lv_obj_set_width(ui_wifiContainersButtons, 250);
    lv_obj_set_height(ui_wifiContainersButtons, 91);
    lv_obj_set_x(ui_wifiContainersButtons, -103);
    lv_obj_set_y(ui_wifiContainersButtons, 14);
    lv_obj_set_align(ui_wifiContainersButtons, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_wifiContainersButtons, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_wifiContainersButtons, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_wifiContainersButtons, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_wifiContainersButtons, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifiContainersButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_wifiContainersButtons, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_wifiContainersButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiConfigButton = lv_btn_create(ui_wifiContainersButtons);
    lv_obj_set_width(ui_wifiConfigButton, 90);
    lv_obj_set_height(ui_wifiConfigButton, 90);
    lv_obj_set_x(ui_wifiConfigButton, -19);
    lv_obj_set_y(ui_wifiConfigButton, -18);
    lv_obj_set_align(ui_wifiConfigButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiConfigButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_wifiConfigButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_wifiConfigButton, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_wifiConfigButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_grayBright);
    ui_object_set_themeable_style_property(ui_wifiConfigButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_grayBright);
    lv_obj_set_style_bg_img_src(ui_wifiConfigButton, &ui_img_9953116, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiResetButton = lv_btn_create(ui_wifiContainersButtons);
    lv_obj_set_width(ui_wifiResetButton, 90);
    lv_obj_set_height(ui_wifiResetButton, 90);
    lv_obj_set_x(ui_wifiResetButton, -19);
    lv_obj_set_y(ui_wifiResetButton, -18);
    lv_obj_set_align(ui_wifiResetButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiResetButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_wifiResetButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_wifiResetButton, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_wifiResetButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_grayBright);
    ui_object_set_themeable_style_property(ui_wifiResetButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_grayBright);
    lv_obj_set_style_bg_img_src(ui_wifiResetButton, &ui_img_788343386, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiLabel = lv_label_create(ui_wifiScreen);
    lv_obj_set_width(ui_wifiLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiLabel, 0);
    lv_obj_set_y(ui_wifiLabel, 200);
    lv_obj_set_align(ui_wifiLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifiLabel, "WIFI");
    ui_object_set_themeable_style_property(ui_wifiLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_grayDark);
    ui_object_set_themeable_style_property(ui_wifiLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_grayDark);
    lv_obj_set_style_text_font(ui_wifiLabel, &ui_font_mono40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_volumeButtonBack2 = lv_imgbtn_create(ui_wifiScreen);
    lv_imgbtn_set_src(ui_volumeButtonBack2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1702299517, NULL);
    lv_obj_set_width(ui_volumeButtonBack2, 50);
    lv_obj_set_height(ui_volumeButtonBack2, 50);
    lv_obj_set_x(ui_volumeButtonBack2, 0);
    lv_obj_set_y(ui_volumeButtonBack2, 150);
    lv_obj_set_align(ui_volumeButtonBack2, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_volumeButtonBack2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_grayBright);
    ui_object_set_themeable_style_property(ui_volumeButtonBack2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_grayBright);

    ui_overlayWifiContainer = lv_obj_create(ui_wifiScreen);
    lv_obj_set_width(ui_overlayWifiContainer, 371);
    lv_obj_set_height(ui_overlayWifiContainer, 300);
    lv_obj_set_align(ui_overlayWifiContainer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_overlayWifiContainer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_overlayWifiContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_overlayWifiContainer, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_overlayWifiContainer, lv_color_hex(0x141414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_overlayWifiContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_overlayWifiLabel1 = lv_label_create(ui_overlayWifiContainer);
    lv_obj_set_width(ui_overlayWifiLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_overlayWifiLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_overlayWifiLabel1, 0);
    lv_obj_set_y(ui_overlayWifiLabel1, -115);
    lv_obj_set_align(ui_overlayWifiLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_overlayWifiLabel1, "Wifi connect");
    ui_object_set_themeable_style_property(ui_overlayWifiLabel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_yellowBright);
    ui_object_set_themeable_style_property(ui_overlayWifiLabel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_yellowBright);
    lv_obj_set_style_text_font(ui_overlayWifiLabel1, &ui_font_mono40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_overlayWifiSSIDLabel = lv_label_create(ui_overlayWifiContainer);
    lv_obj_set_width(ui_overlayWifiSSIDLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_overlayWifiSSIDLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_overlayWifiSSIDLabel, 0);
    lv_obj_set_y(ui_overlayWifiSSIDLabel, -50);
    lv_obj_set_align(ui_overlayWifiSSIDLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_overlayWifiSSIDLabel, "SSID");
    ui_object_set_themeable_style_property(ui_overlayWifiSSIDLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_yellowDark);
    ui_object_set_themeable_style_property(ui_overlayWifiSSIDLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_yellowDark);
    lv_obj_set_style_text_font(ui_overlayWifiSSIDLabel, &ui_font_mono40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_overlayWifiSSIDLabelValue = lv_label_create(ui_overlayWifiContainer);
    lv_obj_set_width(ui_overlayWifiSSIDLabelValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_overlayWifiSSIDLabelValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_overlayWifiSSIDLabelValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_overlayWifiSSIDLabelValue, "market_viewer_setup");
    lv_obj_set_style_text_font(ui_overlayWifiSSIDLabelValue, &ui_font_mono30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_overlayWifiPwdLabel = lv_label_create(ui_overlayWifiContainer);
    lv_obj_set_width(ui_overlayWifiPwdLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_overlayWifiPwdLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_overlayWifiPwdLabel, 0);
    lv_obj_set_y(ui_overlayWifiPwdLabel, 50);
    lv_obj_set_align(ui_overlayWifiPwdLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_overlayWifiPwdLabel, "PASSWORD");
    ui_object_set_themeable_style_property(ui_overlayWifiPwdLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_yellowDark);
    ui_object_set_themeable_style_property(ui_overlayWifiPwdLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_yellowDark);
    lv_obj_set_style_text_font(ui_overlayWifiPwdLabel, &ui_font_mono40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_overlayWifiPwdLabelValue = lv_label_create(ui_overlayWifiContainer);
    lv_obj_set_width(ui_overlayWifiPwdLabelValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_overlayWifiPwdLabelValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_overlayWifiPwdLabelValue, 2);
    lv_obj_set_y(ui_overlayWifiPwdLabelValue, 100);
    lv_obj_set_align(ui_overlayWifiPwdLabelValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_overlayWifiPwdLabelValue, "marketViewer321");
    lv_obj_set_style_text_font(ui_overlayWifiPwdLabelValue, &ui_font_mono30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_wifiConfigButton, ui_event_wifiConfigButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifiResetButton, ui_event_wifiResetButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_volumeButtonBack2, ui_event_volumeButtonBack2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifiScreen, ui_event_wifiScreen, LV_EVENT_ALL, NULL);

}

void ui_wifiScreen_screen_destroy(void)
{
    if(ui_wifiScreen) lv_obj_del(ui_wifiScreen);

    // NULL screen variables
    ui_wifiScreen = NULL;
    ui_mainContainerWifi = NULL;
    ui_connectionInfoContainer = NULL;
    ui_wifiConnectionRoundIndicator = NULL;
    ui_connectionLabel = NULL;
    ui_connectedWifiContainer = NULL;
    ui_wifiNameContainer = NULL;
    ui_connectedWifiSSIDLabel = NULL;
    ui_connectedWifiIcon = NULL;
    ui_backendUrlLabel = NULL;
    ui_wifiContainersButtons = NULL;
    ui_wifiConfigButton = NULL;
    ui_wifiResetButton = NULL;
    ui_wifiLabel = NULL;
    ui_volumeButtonBack2 = NULL;
    ui_overlayWifiContainer = NULL;
    ui_overlayWifiLabel1 = NULL;
    ui_overlayWifiSSIDLabel = NULL;
    ui_overlayWifiSSIDLabelValue = NULL;
    ui_overlayWifiPwdLabel = NULL;
    ui_overlayWifiPwdLabelValue = NULL;

}
